version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "01:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.firebase:firebase-auth
    versions:
    - 20.0.2
    - 20.0.3
